### ISSUE TITLE
Generating in-repo-engine fails with EmberCLI 2.13.0-beta.1

### ISSUE THREAD

**Issue by mike183** [ember-engines/ember-engines#366]
The error appears to be coming from [here](https://github.com/ember-engines/ember-engines/blob/master/blueprints/in-repo-engine/index.js#L67-L69), and doesn't occur after reverting back to EmberCLI 2.12.0.

Error:
```
this._readJsonSync is not a function
TypeError: this._readJsonSync is not a function
    at Class._generatePackageJson (/Users/{USER}/Desktop/test-app/node_modules/ember-cli/blueprints/in-repo-addon/index.js:32:25)
    at Class._generatePackageJson (/Users/{USER}/Desktop/test-app/node_modules/ember-engines/blueprints/in-repo-engine/index.js:85:38)
    at Class.afterInstall (/Users/{USER}/Desktop/test-app/node_modules/ember-cli/blueprints/in-repo-addon/index.js:23:10)
    at Class.afterInstall (/Users/{USER}/Desktop/test-app/node_modules/ember-engines/blueprints/in-repo-engine/index.js:75:30)
    at tryCatch (/Users/{USER}/Desktop/test-app/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/{USER}/Desktop/test-app/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/{USER}/Desktop/test-app/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/{USER}/Desktop/test-app/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rwjblue** [comment]
Introduced by https://github.com/ember-cli/ember-cli/commit/2eff23cece2d50ad5d57ab4d71822dbb2e4ee838. We need to define a `_readJsonSync` in our blueprint.
