### ISSUE TITLE
this._addonPostprocessTree is not a function

### ISSUE THREAD

**Issue by RayKwon** [ember-engines/ember-engines#332]
Hi team, thank you all for great addon.

I have been using ember-engies@0.4.0 in my project and was working very well, but I got the error message, "this._addonPostprocessTree is not a function" when I turn on "lazyLoading" after upgrading to 0.5.0-beta7
That error is gone once I turn off "lazyLoading".
Any idea? Looks like a bug.

**Comment by rwjblue** [comment]
ember-engines@0.5.x requires ember-cli@2.12.0-beta.1 or higher (which introduce the method in question).

**Comment by RayKwon** [comment]
Thanks @rwjblue I will try to update ember-cli

**Comment by kiwiupover** [comment]
@RayKwon you will also need to update EmberJS to  2.12.x
